[postgresql]
dsn="postgres://chirpstack_user:ecotrack_super_secret@db:5432/chirpstack?sslmode=disable"

[redis]
servers=["redis://redis:6379"]

[network]
net_id="000000"
enabled_regions=["au915_0"]

# Ajuste feito aqui no nome do bloco:
[integration.mqtt]
server="tcp://mosquitto:1883"
json=true

[api]
bind="0.0.0.0:8080"
secret="ecotrack-secret-key"
