[[regions]]
id="au915_0"
description="AU915 (Frequencia Brasileira)"
common_name="AU915"

[regions.network]
installation_margin=10
rx_window=1
rx1_delay=1
rx1_dr_offset=0
rx2_dr=8
rx2_frequency=923300000
downlink_tx_power=-1

[regions.gateway.backend]
type="mqtt"

[regions.gateway.backend.mqtt]
server="tcp://mosquitto:1883"
event_topic="au915_0/gateway/+/event/+"
command_topic_template="au915_0/gateway/{{ .GatewayID }}/command/{{ .CommandType }}"
