default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  user: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "ecotrack_development") %>

  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "ecotrack_development") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "ecotrack_development") %>
    migrations_paths: db/cable_migrate

  cache:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "ecotrack_development") %>
    migrations_paths: db/cache_migrate
